name: Docker Image CI

on:
  push:
    branches: [ "feature/test" ]

jobs:
  runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: scrd
        password: dckr_pat_ll4cdKCxTTRvO280vxQVCq8NOfA
        #password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: scaredste/alert-tracker:latest
