name: Docker Image CI

on:
  push:
    branches:
      - "feature/test"

jobs:
  build: # Job name
    name: Build, package, and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Build and package Spring Boot application with Maven
        run: ./mvnw clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: scaredste
          password: dckr_pat_ll4cdKCxTTRvO280vxQVCq8NOfA
          #password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: scaredste/alert-tracker:latest
